#display-osinfo.msh
#Displays OS information
#Author Thomas Lee - tfl@psp.co.uk
#Tested with PowerShell RC1.1

$os = Get-WMIObject Win32_OperatingSystem
"Operating System Information for $($os.CSName)"
"--------------------------------"
""
"Boot Device:                $($os.BootDevice)"
"Build Number                $($os.BuildNumber)"
"Build Type                  $($os.BuildType)"
"Caption                     $($os.Caption)"
"Code Set                    $($os.CodeSet)"
"Country Code                $($os.CountryCode)"
"Creation Class Name         $($os.CreationClassName)"
"CS CreationClassName        $($os.CSCreationClassName)" 
"CSD Version                 $($os.CSDVersion)"
"CS Name                     $($os.CSName)"
"Current Time Zone           $($os.CurrentTimeZone)"
"DEP-32BitApplications       $($os.DataExecutionPrevention_32BitApplications)"
"DEP-Available               $($os.DataExecutionPrevention_Available)"
"DEP-Drivers                 $($os.DataExecutionPrevention_Drivers)"
"DEP-Support Policy          $($os.DataExecutionPrevention_SupportPolicy)"
"Debug                       $($os.Debug)"
"Description                 $($os.Description)"
"Distributed                 $($os.Distributed)"
"Encryption Level            $($os.EncryptionLevel)"
"Foreground Appl Boost       $($os.ForegroundApplicationBoost)"
"Free Physical Memory        $($os.FreePhysicalMemory)"
"Free Space In Paging Files  $($os.FreeSpaceInPagingFiles)"
"Free Virtual Memory         $($os.FreeVirtualMemory)"
"Install Date                $($os.InstallDate)"
"Large System Cache          $($os.LargeSystemCache)"
"Last Boot Up Time           $($os.LastBootUpTime)"
"Local Date Time             $($os.LocalDateTime)"
"Locale                      $($os.Locale)"
"Manufacturer                $($os.Manufacturer)"
"MaxN umber Of Processes     $($os.MaxNumberOfProcesses)"
"Max Process Memory Size     $($os.MaxProcessMemorySize)"
"Name                        $($os.Name)"
"Number Of Licensed Users    $($os.NumberOfLicensedUsers)"
"Number Of Processes         $($os.NumberOfProcesses)"
"Number Of Users             $($os.NumberOfUsers)"
"Organization                $($os.Organization)"
"OS Language                 $($os.OSLanguage)"
"OS Product Suite            $($os.OSProductSuite)"
"OS Type                     $($os.OSType)"
"Other Type Description      $($os.OtherTypeDescription)"
"Plus Product ID             $($os.PlusProductID)"
"Plus Version Number         $($os.PlusVersionNumber)"
"Primary                     $($os.Primary)"
"Product Type                $($os.ProductType)"
"Quantum Length              $($os.QuantumLength)"
"Quantum Type                $($os.QuantumType)"
"Registered User             $($os.RegisteredUser)"
"Serial Number               $($os.SerialNumber)"
"Service Pack Major Version  $($os.ServicePackMajorVersion)"
"Service Pack Minor Version  $($os.ServicePackMinorVersion)"
"Size Stored In Paging Files $($os.SizeStoredInPagingFiles)"
"Suite Mask                  $($os.SuiteMask)"
"System Device               $($os.SystemDevice)"
"System Directory            $($os.SystemDirectory)"
"System Drive                $($os.SystemDrive)"
"Total Swap Space Size       $($os.TotalSwapSpaceSize)"
"Total Virtual Memory Size   $($os.TotalVirtualMemorySize)"
"Total Visible Memory Size   $($os.TotalVisibleMemorySize)"
"Version                     $($os.Version)"
"Windows Directory           $($os.WindowsDirectory)"
